### ISSUE TITLE
Требует PHP модуль MySQL при установке

### ISSUE THREAD

**Issue by NaikSoftware** [john-cms/johncms#2]
Как известно, mysql 100 лет как устарел, но по крайней мере в установщике он используется, и даже есть такая проверка https://github.com/john-cms/johncms/blob/master/.install/setup/index.php#L27

Соотв. на PHP 7 невозможно установить. Если дело только в установщике, то можно же перейти на mysqli

**Comment by professor93** [comment]
пеерейти на PDO

**Comment by Gazenwagen** [comment]
Работа уже ведется, думаю, что PDO будет.

**Comment by Gazenwagen** [comment]
Переход на PDO завершен
