### ISSUE TITLE
Сделать класс для работы с постраничной навигацией не привязанный к БД

### ISSUE THREAD

**Issue by simba77** [john-cms/johncms#210]
Сделать класс для работы с постраничной навигацией не привязанный к БД.
Будет использоваться например в ip активности модуля онлайн и подобных страницах

**Comment by Compolomus** [comment]
https://github.com/Compolomus/Pagination не пойдет?

**Comment by Compolomus** [comment]
Закрываем?

**Comment by simba77** [comment]
> Закрываем?

Ага. Только зарелизь)
