### ISSUE TITLE
Отвязка от старого ядра

### ISSUE THREAD

**Issue by Gazenwagen** [john-cms/johncms#23]
Все модули и скрипты, входящие в дистрибутив, ДОЛЖНЫ использовать только новое ядро.

**Comment by Compolomus** [comment]
то есть что раньше в ядре было, теперь будет во всез местах, где оно требуется?

**Comment by Gazenwagen** [comment]
Сейчас стоит задача как можно больше отвязаться от старого ядра.
Всякие глобальные переменные, которые неизвестно откуда берутся, выпиливаются в первую очередь.
